'use strict';

const DIRECTION = {
	LEFT: 'LEFT',
	RIGHT: 'RIGHT',
	STOP: 'STOP',
	UP: 'UP'
};

const GAMEOBJECT = {
	BALL: 'BALL',
	DUDE: 'DUDE',
	OBSTACLE: 'OBSTACLE'
}

const MODE = {
	ONE_PLAYER_MODE: 'ONE_PLAYER_MODE',
	TWO_PLAYER_MODE: 'TWO_PLAYER_MODE',
	MULTI_PLAYER_MODE: 'MULTI_PLAYER_MODE'
}

const STATE = {
	RUNNING: 'RUNNING',
	STOPPED: 'STOPPED'
}

const PLAYER ={
	ONE: true,
	TWO: false
}
let BALL_RADIUS = 20;
let DUDE_RADIUS = 70;

const BALL_COLOUR = '#FF5733'; 
const DUDE_COLOUR = '#f9e711';
const DEBUG_COLOUR = '#E116C0';
const BARRIER_COLOUR = '#000000'; 

const WIDTH = 1200;
const HEIGHT = 700;

const PARKINSON_PREVENTION = 7;

const MENU_FONT = "50px 'Lilita One";
const MENU_FONT_COLOUR = '#09C60B';
const MENU_FONT_COLOUR_ACTIVE = '#E116C0';

const ENDING_TEXT_STYLING = "16px 'Lilita One";

const WIDTH_BARRIER = 5;
const HEIGHT_BARRIER = 75;

const MOVEMENT_TICKS_SIZE = 0.1; 
let MAX_SPEED_DUDE = 5;
let MAX_SPEED_BALL = 10;
const FRAME_SPEED_MS = 8;
const APPLY_FRICTION_BOUNCE = true; 
const HORIZONTAL_MOMENTUM = 0.7;
const GRAVITY = 0.09;
const INITAL_JUMP_VELOCITY = 5.4; 

const DUDE_FRICTION = 0.92;
const GROUND_FRICTION = -0.86; 
const WALL_FRICTION = -1.00